# Build stage
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /app

# Copy everything
COPY . .

# Restore dependencies
RUN dotnet restore

# FIX: Point directly to the .csproj file of your API project
# This prevents the "Solution-level output" warning
RUN dotnet publish GeoVibs_Busisness_API/GeoVibs_Busisness_API.csproj -c Release -o out

# Run stage
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

# Copy the published files from the build stage
COPY --from=build /app/out .

# Render uses port 10000 by default for Web Services
ENV ASPNETCORE_URLS=http://+:10000
EXPOSE 10000

# Ensure this matches the actual DLL name generated by your project
ENTRYPOINT ["dotnet", "GeoVibs_Busisness_API.dll"]